import { NumberFormat } from '../../src'

test('when the value is invalid with default config', () => {
  const numberFormat = new NumberFormat({})
  test('should return as follows', () => {
    expect(numberFormat.format('')).toEqual('')
    expect(numberFormat.format('foo')).toEqual('')
    expect(numberFormat.format('-foo')).toEqual('')
    expect(numberFormat.format('-fo,o-')).toEqual('')
    expect(numberFormat.format('!@#$%^&*()')).toEqual('')
  })
  test('should return as follows', () => {
    expect(numberFormat.format('')).toEqual('')
    expect(numberFormat.format('foo')).toEqual('')
    expect(numberFormat.format('-foo')).toEqual('')
    expect(numberFormat.format('-fo,o-')).toEqual('')
    expect(numberFormat.format('!@#$%^&*()')).toEqual('')
  })
  test('should return as follows', () => {
    expect(numberFormat.unformat('')).toEqual('')
    expect(numberFormat.unformat('foo')).toEqual('')
    expect(numberFormat.unformat('-foo')).toEqual('')
    expect(numberFormat.unformat('-fo,o-')).toEqual('')
    expect(numberFormat.unformat('!@#$%^&*()')).toEqual('')
  })
})
test('format when options are default', () => {
  const numberFormat = new NumberFormat({})
  test('format string value', () => {
    expect(numberFormat.format('')).toEqual('')
    expect(numberFormat.format('0')).toEqual('0')
    expect(numberFormat.format('0.')).toEqual('0')
    expect(numberFormat.format('-0.0')).toEqual('0')
    expect(numberFormat.format('0.10')).toEqual('0.1')
    expect(numberFormat.format('0.0-')).toEqual('0')
    expect(numberFormat.format('0.10-')).toEqual('-0.1')
    expect(numberFormat.format('12,345.54921')).toEqual('12,345.55')
    expect(numberFormat.format('--12,345.12345')).toEqual('-12,345.12')
    expect(numberFormat.format('12,345.54321.12345')).toEqual('12,345.54')
    expect(numberFormat.format('-12,345..54321-')).toEqual('-12,345.54')
  })
  test('format numerical value', () => {
    expect(numberFormat.format(0)).toEqual('0')
    expect(numberFormat.format(0)).toEqual('0')
    expect(numberFormat.format(0.0)).toEqual('0')
    expect(numberFormat.format(-0.1)).toEqual('-0.1')
    expect(numberFormat.format(-0.0)).toEqual('0')
    expect(numberFormat.format(0.1)).toEqual('0.1')
    expect(numberFormat.format(12345.54921)).toEqual('12,345.55')
    expect(numberFormat.format(12345.12345)).toEqual('12,345.12')
    expect(numberFormat.format(12345.54321)).toEqual('12,345.54')
    expect(numberFormat.format(12345.54321)).toEqual('12,345.54')
  })
})
